### ISSUE TITLE
데이터 내보내기 기능이 작동하지 않음

### ISSUE THREAD

**Issue by unstabler** [twingyeo-kr/notice#7]
# 조사 결과
- 백업 아카이브 생성까지는 성공하나, 업로드 과정에서 다음과 같은 오류가 발생 

```
Aws::S3::Errors::SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
```

## TODO

- [x] 설정 파일 확인: 음.. 이미지 업로드는 잘 작동하던데..
- [x] upstream에 보고 필요할려나..

**Comment by unstabler** [comment]
예상하기로는 https://github.com/tootsuite/mastodon/blob/1b282299df67b0b9681e8d396fbe98f687ff9bba/app/services/backup_service.rb#L57 호출에서 Content-Type 헤더가 잘못 지정되어있거나 싶은 예상이 드는데 실제로 확인이 필요할듯 
( https://github.com/googleapis/google-cloud-ruby/issues/1964 랑 비슷한 사례인 것 같음 )

**Comment by unstabler** [comment]
예상 적중하였고 https://github.com/tootsuite/mastodon/issues/9273 https://github.com/tootsuite/mastodon/pull/9274 를 업스트림에 제출하였으나 전 영어를 정말 할 줄 몰라서 이거 제출하는게 뭔가 민폐가 되지 않을까 하는 엉엉 무서어 살려줘

**Comment by unstabler** [comment]
음, 이게 완전한 원인이 아닌 것 같아..

**Comment by unstabler** [comment]
```
Nov 12 23:47:17 twingyeo.kr bundle[15827]: 2018-11-12T23:47:17.083Z 15827 TID-ovircmlcv BackupWorker JID-59313d511dcd14e72548da35 INFO: fail: 248.584 sec
Nov 12 23:47:17 twingyeo.kr bundle[15827]: 2018-11-12T23:47:17.083Z 15827 TID-ovircmlcv WARN: {"context":"Job raised exception","job":{"class":"BackupWorker","args":[31],"retry":5,"queue":"pull","backtrace":true,"dead":false,"jid":"59313d511dcd14e72548da35","created_at":1542065258.0115583,"enqueued_at":1542066012.4948342,"error_message":"The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.","error_class":"Aws::S3::Errors::SignatureDoesNotMatch","failed_at":1542065701.3881736,"retry_count":1,"error_backtrace":["/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.35.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.23.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.23.0/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.23.0/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.35.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.35.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.35.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.35.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.35.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-3.35.0/lib/seahorse/client/request.rb:70:in `send_request'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.23.0/lib/aws-sdk-s3/client.rb:887:in `create_multipart_upload'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.23.0/lib/aws-sdk-s3/multipart_file_up
Nov 12 23:47:17 twingyeo.kr bundle[15827]: loader.rb:52:in `initiate_upload'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.23.0/lib/aws-sdk-s3/multipart_file_uploader.rb:43:in `upload'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.23.0/lib/aws-sdk-s3/file_uploader.rb:32:in `upload'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/aws-sdk-s3-1.23.0/lib/aws-sdk-s3/customizations/object.rb:308:in `upload_file'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/paperclip-6.0.0/lib/paperclip/storage/s3.rb:379:in `block in flush_writes'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/paperclip-6.0.0/lib/paperclip/storage/s3.rb:352:in `each'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/paperclip-6.0.0/lib/paperclip/storage/s3.rb:352:in `flush_writes'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/paperclip-6.0.0/lib/paperclip/attachment.rb:247:in `save'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/paperclip-6.0.0/lib/paperclip/has_attached_file.rb:92:in `block in add_active_record_callbacks'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `instance_exec'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:517:in `block in invoke_after'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:517:in `each'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:517:in `invoke_after'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:133:in `run_callbacks'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_
Nov 12 23:47:17 twingyeo.kr bundle[15827]: run_save_callbacks'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/callbacks.rb:342:in `create_or_update'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/persistence.rb:308:in `save!'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/validations.rb:52:in `save!'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:315:in `block in save!'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'","/home/mastodon/.rbenv/versions/2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/transactions.rb:315:in `save!'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/suppressor.rb:48:in `save!'","/home/mastodon/live/app/services/backup_service.rb:57:in `build_archive!'","/home/mastodon/live/app/se
Nov 12 23:47:17 twingyeo.kr bundle[15827]: rvices/backup_service.rb:13:in `call'","/home/mastodon/live/app/workers/backup_worker.rb:21:in `perform'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:185:in `execute_job'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'","/home/mastodon/live/app/lib/sidekiq_error_handler.rb:5:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-unique-jobs-5.0.10/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:166:in `block in process'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/job_retry.rb:98:in `local'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.2/lib/sidekiq/rails.rb:42:in `block in call'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/reloader.rb:73:in `block in wrap'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'","/home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/
N
```

**Comment by unstabler** [comment]
notice@twingyeo.kr 계정으로는 아카이브 생성이 잘 되는 것 같은데 좀 용량이 큰 애들만 아카이브 생성이 안되는 것 같다 @ @);;;

**Comment by unstabler** [comment]
으으, 추가 테스트가 필요하겠군..

**Comment by unstabler** [comment]
signature method 관련 문제인 것 같은데 뭔가 엄청나게 꼬인 것 같은데......
https://github.com/aws/aws-sdk-ruby/issues/1151

**Comment by unstabler** [comment]
으.. 대강 파악한 것 같다..
- 아카이브 크기가 커지면 Paperclip/fog는 파일을 분할하여 chunked(multipart) upload를 시도하는 모양.
- Google Cloud Storage의 S3 호환 API가 multipart upload를 지원하지 않는다는 얘기도 있고 paperclip/aws-sdk-ruby쪽에서의 multipart upload 시 signature 계산이 google쪽과 맞지 않는 것일 수도 있다.. 엉엉..

**Comment by unstabler** [comment]
뭔가 이거 제가 해결할 수 있는 범위를 벗어난 것 같은데.....,,,,

**Comment by toniree** [comment]
Content-type="text/plain" 지워보세요

**Comment by unstabler** [comment]
@toniree 조언 감사합니다.

**Comment by unstabler** [comment]
도저히 해결할 방법이 생각나지 않아, Google Cloud Storage에서 AWS S3으로 데이터를 전부 옮겨버림으로 해결하였습니다.
